CREATE DATABASE AFTERNOON_SESSION;
USE AFTERNOON_SESSION;

CREATE TABLE CATEGORY(
	ID INT NOT NULL AUTO_INCREMENT,
    NOM VARCHAR(30) NOT NULL,
    CONSTRAINT PRIMARY KEY (ID)
);
CREATE TABLE MOVIE(
	CODE VARCHAR(10) NOT NULL,
    TITLE VARCHAR(40) NOT NULL,
    LENGHT VARCHAR(8) NOT NULL,
    IDCATEGORY INT NULL,
    CONSTRAINT PRIMARY KEY (CODE),
    CONSTRAINT FK_CATEGORY FOREIGN KEY (IDCATEGORY) REFERENCES CATEGORY(ID) ON DELETE SET NULL
);

INSERT INTO CATEGORY (NOM) VALUES ('VIOLÊNCIA');
INSERT INTO CATEGORY (NOM) VALUES ('COMÉDIA');
INSERT INTO CATEGORY (NOM) VALUES ('DARMA');
INSERT INTO CATEGORY (NOM) VALUES ('MISTÉRIO');
INSERT INTO CATEGORY (NOM) VALUES ('TERROR');
INSERT INTO CATEGORY (NOM) VALUES ('AVENTURA');
INSERT INTO MOVIE (CODE,TITLE,LENGHT) VALUES  ('FHPPA','HERRÉ POTTA','02:52:35');
INSERT INTO MOVIE VALUES  ('FANDG','A NAMORADA DO GUSTAVO','03:40:50',4);
INSERT INTO MOVIE VALUES  ('FOBVP2','O BICHO VAI PEGAR 2','01:40:21',6);
INSERT INTO MOVIE VALUES  ('FOM3','OS MERCENÁRIOS 3','01:56:32',1);
INSERT INTO MOVIE VALUES  ('FIAC','IT A COISA','02:05:31',5);
INSERT INTO MOVIE VALUES  ('FC','CORRA','01:50:42',1);
INSERT INTO MOVIE VALUES  ('FSH2','SHERLOCK HOLMES 2','02:05:12',4);
INSERT INTO MOVIE VALUES  ('FSPCOM','SCOTT PIGRIM CONTRA 0 MUNDO','01:42:56',6);

UPDATE CATEGORY SET NOM = 'DRAMA' WHERE ID = 3;
UPDATE MOVIE SET TITLE = 'HARRY POTTER' WHERE CODE = 'FHPPA';
UPDATE MOVIE SET IDCATEGORY = 1 WHERE CODE = 'FHPPA';
DELETE FROM CATEGORY WHERE ID = 2;

INSERT INTO CATEGORY (NOM) VALUES ('PROMOÇÃO');

SELECT F.TITLE, F.IDCATEGORY
FROM MOVIE F
WHERE F.LENGHT > '02:30:00';

SELECT F.TITLE, C.NOM
FROM MOVIE F LEFT JOIN CATEGORY C
ON F.IDCATEGORY = C.ID;
