CREATE DATABASE BD1_2023;
USE BD1_2023;

CREATE TABLE GRADE(
	ID INT NOT NULL,
    ANO INT NOT NULL,
    MAJOR VARCHAR(20) NOT NULL,
    CONSTRAINT PRIMARY KEY(ID)
);

CREATE TABLE STUDENT(
	RA VARCHAR(7) NOT NULL,
    NOM VARCHAR(30) NOT NULL,
    MOMENT DATE NOT NULL,
    IDGRADE INT NOT NULL,
    CONSTRAINT PRIMARY KEY(RA),
    CONSTRAINT FK_STUDENT FOREIGN KEY(IDGRADE) REFERENCES GRADE(ID) ON UPDATE CASCADE ON DELETE RESTRICT 
    );

CREATE TABLE ADDRESS(
	ADDRESS VARCHAR(50) NOT NULL,
    RASTUDENT VARCHAR(7) NOT NULL,
    CONSTRAINT PRIMARY KEY (RASTUDENT,ADDRESS),
    CONSTRAINT FK_ADDRESS FOREIGN KEY(RASTUDENT) REFERENCES STUDENT(RA) ON UPDATE CASCADE ON DELETE CASCADE 
); 
  

CREATE TABLE SUBJECT(
	COD3 VARCHAR(10) NOT NULL,
    NOM VARCHAR(20) NOT NULL,
    IDGRADE INT NOT NULL,
    CONSTRAINT PRIMARY KEY(COD3),
    CONSTRAINT FK_SUBJECT FOREIGN KEY(IDGRADE) REFERENCES GRADE(ID) ON UPDATE CASCADE ON DELETE CASCADE
);

INSERT INTO GRADE(ANO,ID,MAJOR) VALUES(2021,202021,'TÉCNICO EM INFORMÁTICA');
INSERT INTO STUDENT VALUES('0064531', 'MOISÉS PEREIRA', str_to_date('13/05/1982', '%d/%m/%Y'), 202021);

SELECT * FROM GRADE;
SELECT * FROM STUDENT;

CREATE USER 'ZEDASCOUVE'@'LOCALHOST' IDENTIFIED BY '123TESTANDO';

GRANT SELECT, INSERT 
ON AULABD2.*
TO 'ZEDASCOUVE'@'LOCALHOST';
