CREATE DATABASE POOR_UNCLE;
USE POOR_UNCLE;

CREATE TABLE CLIENT(CPF VARCHAR(14) NOT NULL, NOM VARCHAR(50) NOT NULL, AGE INT NOT NULL, CONSTRAINT PRIMARY KEY(CPF));
CREATE TABLE ADDRESS(CLIENT_CPF VARCHAR(14) NOT NULL, DESCRI VARCHAR(200) NOT NULL, CONSTRAINT PRIMARY KEY(CLIENT_CPF,DESCRI), CONSTRAINT FK_CLIENT_ADDRESS FOREIGN KEY(CLIENT_CPF) REFERENCES CLIENT(CPF) ON DELETE CASCADE);
CREATE TABLE ACCOUNT(NUM INT NOT NULL, BALANCE DOUBLE NOT NULL, CLIENT_CPF VARCHAR(14) NOT NULL, CONSTRAINT PRIMARY KEY(NUM), CONSTRAINT FK_CLIENT_ACCOUNT FOREIGN KEY(CLIENT_CPF) REFERENCES CLIENT(CPF) ON DELETE RESTRICT);

INSERT INTO CLIENT VALUES('013.976.896-33','MOISÉS',40);
INSERT INTO ADDRESS VALUES('013.976.896-33','RUA XABLAU,1');
INSERT INTO ACCOUNT VALUES(1582,18.537,'013.976.896-33');
